// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_vo.proto

package com.sun.lib.grpc.vo;

public final class UserVo {
  private UserVo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sun_lib_grpc_vo_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sun_lib_grpc_vo_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sun_lib_grpc_vo_UserResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sun_lib_grpc_vo_UserResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sun_lib_grpc_vo_AddUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sun_lib_grpc_vo_AddUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ruser_vo.proto\022\023com.sun.lib.grpc.vo\"E\n\013" +
      "UserRequest\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\013\n" +
      "\003age\030\003 \001(\005\022\017\n\007address\030\004 \001(\t\"B\n\010UserResp\022" +
      "\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\017" +
      "\n\007address\030\004 \001(\t\"D\n\007AddUser\022\014\n\004name\030\001 \001(\t" +
      "\022\013\n\003age\030\002 \001(\005\022\017\n\007address\030\003 \001(\t\022\r\n\005phone\030" +
      "\004 \003(\tB\037\n\023com.sun.lib.grpc.voB\006UserVoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_sun_lib_grpc_vo_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sun_lib_grpc_vo_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sun_lib_grpc_vo_UserRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "Address", });
    internal_static_com_sun_lib_grpc_vo_UserResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sun_lib_grpc_vo_UserResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sun_lib_grpc_vo_UserResp_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "Address", });
    internal_static_com_sun_lib_grpc_vo_AddUser_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_sun_lib_grpc_vo_AddUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sun_lib_grpc_vo_AddUser_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", "Phone", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
