// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_dto.proto

package com.sun.lib.grpc.user.dto;

public interface AddUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sun.lib.grpc.user.dto.AddUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>string address = 3;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 3;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
