// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_dto.proto

package com.sun.lib.grpc.user.dto;

public final class UserDto {
  private UserDto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sun_lib_grpc_user_dto_SearchUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sun_lib_grpc_user_dto_SearchUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sun_lib_grpc_user_dto_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sun_lib_grpc_user_dto_UserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sun_lib_grpc_user_dto_AddUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sun_lib_grpc_user_dto_AddUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sun_lib_grpc_user_dto_UserList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sun_lib_grpc_user_dto_UserList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016user_dto.proto\022\031com.sun.lib.grpc.user." +
      "dto\"K\n\021SearchUserRequest\022\n\n\002id\030\001 \001(\005\022\014\n\004" +
      "name\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\017\n\007address\030\004 \001(\t" +
      "\"F\n\014UserResponse\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001" +
      "(\t\022\013\n\003age\030\003 \001(\005\022\017\n\007address\030\004 \001(\t\"<\n\016AddU" +
      "serRequest\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\017\n" +
      "\007address\030\003 \001(\t\"I\n\010UserList\022=\n\014userRespon" +
      "se\030\001 \003(\0132\'.com.sun.lib.grpc.user.dto.Use" +
      "rResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_sun_lib_grpc_user_dto_SearchUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sun_lib_grpc_user_dto_SearchUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sun_lib_grpc_user_dto_SearchUserRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "Address", });
    internal_static_com_sun_lib_grpc_user_dto_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sun_lib_grpc_user_dto_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sun_lib_grpc_user_dto_UserResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "Address", });
    internal_static_com_sun_lib_grpc_user_dto_AddUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_sun_lib_grpc_user_dto_AddUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sun_lib_grpc_user_dto_AddUserRequest_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", });
    internal_static_com_sun_lib_grpc_user_dto_UserList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_sun_lib_grpc_user_dto_UserList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sun_lib_grpc_user_dto_UserList_descriptor,
        new java.lang.String[] { "UserResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
