// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_dto.proto

package com.sun.lib.grpc.user.dto;

public interface UserListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sun.lib.grpc.user.dto.UserList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.sun.lib.grpc.user.dto.UserResponse userResponse = 1;</code>
   */
  java.util.List<com.sun.lib.grpc.user.dto.UserResponse> 
      getUserResponseList();
  /**
   * <code>repeated .com.sun.lib.grpc.user.dto.UserResponse userResponse = 1;</code>
   */
  com.sun.lib.grpc.user.dto.UserResponse getUserResponse(int index);
  /**
   * <code>repeated .com.sun.lib.grpc.user.dto.UserResponse userResponse = 1;</code>
   */
  int getUserResponseCount();
  /**
   * <code>repeated .com.sun.lib.grpc.user.dto.UserResponse userResponse = 1;</code>
   */
  java.util.List<? extends com.sun.lib.grpc.user.dto.UserResponseOrBuilder> 
      getUserResponseOrBuilderList();
  /**
   * <code>repeated .com.sun.lib.grpc.user.dto.UserResponse userResponse = 1;</code>
   */
  com.sun.lib.grpc.user.dto.UserResponseOrBuilder getUserResponseOrBuilder(
      int index);
}
